using System.Text.Json;
using Avalonia;
using Avalonia.Controls;
using Avalonia.Headless;
using Avalonia.Interactivity;
using Avalonia.Media.Imaging;
using Avalonia.Styling;
using Avalonia.Threading;
using Avalonia.VisualTree;
using AvaMedia.Core;
using AvaMedia.Desktop;

var root=Path.GetFullPath("artifacts/functions-"+DateTime.Now.ToString("yyyyMMdd-HHmmss"));Directory.CreateDirectory(root);
var engine=new MediaEngine(new());var results=new List<string>();var outputs=new List<string>();
void Check(bool value,string message){if(!value)throw new Exception(message);results.Add(message);Console.WriteLine("PASS "+message);}
async Task FF(params string[] args){var r=await ProcessRunner.Run(engine.FFmpeg,args);if(r.ExitCode!=0)throw new Exception(r.Error);}
var first=Path.Combine(root,"first.mp4");var second=Path.Combine(root,"second.mp4");
await FF("-v","error","-n","-f","lavfi","-i","testsrc2=size=320x180:rate=25","-f","lavfi","-i","sine=frequency=440:sample_rate=44100","-t","4","-c:v","mpeg4","-q:v","3","-c:a","aac","-metadata","title=AvaMedia test",first);
await FF("-v","error","-n","-f","lavfi","-i","testsrc2=size=240x320:rate=25","-f","lavfi","-i","sine=frequency=880:sample_rate=44100","-t","3","-c:v","mpeg4","-q:v","3","-c:a","aac",second);
async Task<Job> Run(string name,string id,ConversionOptions o,string[]? inputs=null,List<ConversionOptions>? perInput=null,bool folder=false)
{
    var job=new Job{FeatureId=id,Inputs=inputs??[first],InputOptions=perInput,Options=o,Output=MediaEngine.UniqueOutput(root,name,o.Format,directory:folder)};
    await engine.Execute(job,_=>{},CancellationToken.None);outputs.Add(job.Output);return job;
}
var rate=await Run("rate","mp4",new(){SampleRate=32000,AudioChannels=1});var ri=await engine.Probe(rate.Output);Check(ri.AudioSampleRate==32000&&ri.AudioChannels==1,"Video output applies sample rate and channels");
var late=await Run("join-late","join",new(){Start=4.5,End=6.5},[first,second]);var li=await engine.Probe(late.Output);Check(li.Duration is >1.85 and <2.2,"Joined timeline can start after the first input ends");
var per=await Run("join-edits","join",new(){},[first,second],[new(){Start=1,End=3,Speed=2,CropWidth=200,CropHeight=100},new(){Start=.5,End=2.5,Speed=.5}]);Check((await engine.Probe(per.Output)).Duration is >4.8 and <5.3,"Join applies each input interval and speed independently");
var muted=await Run("join-muted","join",new(){Mute=true},[first,second]);Check(!(await engine.Probe(muted.Output)).HasAudio,"Joined video mute removes audio streams");
var mix=await Run("mix-longest","audio-mix",new(){Format="wav"},[second,first]);Check((await engine.Probe(mix.Output)).Duration is >3.95 and <4.15,"Audio mix uses the longest input duration");
var mux=await Run("mux-edits","mux",new(){Format="mkv"},[first,second],[new(){Start=1,End=3,CropWidth=200,CropHeight=100},new(){Start=.5,End=2.5,Volume=.5}]);var mi=await engine.Probe(mux.Output);Check(mi.Width==200&&mi.Height==100&&mi.HasAudio&&mi.Duration is >1.9 and <2.2,"Mux applies independent source edits");
var meta=await Run("metadata-drop","mp4",new(){KeepMetadata=false});using(var doc=JsonDocument.Parse((await engine.Probe(meta.Output)).RawJson))Check(!doc.RootElement.GetProperty("format").GetProperty("tags").TryGetProperty("title",out _),"Metadata checkbox removes source title");
var good=await Run("quality-high","mp4",new(){Quality=4});var small=await Run("quality-low","mp4",new(){Quality=48});Check(new FileInfo(good.Output).Length>new FileInfo(small.Output).Length*1.15,"Video quality setting changes encoded output");
var frames=await Run("frames-half","frames",new(){Format="png",FrameInterval=.5},folder:true);Check(Directory.GetFiles(frames.Output,"*.png").Length==8,"Frame interval exports the correct number of images");
var ico=await Run("icon64","image-ico",new(){Format="ico",Width=64,Height=64});Check((await engine.Probe(ico.Output)).Width==64,"ICO respects selected dimensions");
var rotated=await Run("rotate","image-png",new(){Format="png",Rotation=90,Flip=true});var rot=await engine.Probe(rotated.Output);Check(rot.Width==180&&rot.Height==320,"Image rotation swaps dimensions");
var edge=await Run("edge-watermark","delogo",new(){DelogoX=0,DelogoY=0,DelogoWidth=80,DelogoHeight=40});Check((await engine.Probe(edge.Output)).Width==320,"Watermark removal works at the frame edge");
var subtitle=Path.Combine(root,"字幕 O'Brien [test],.srt");await File.WriteAllTextAsync(subtitle,"1\n00:00:00,000 --> 00:00:03,900\nAvaMedia subtitle\n");
var sub=await Run("subtitles","mp4",new(){Subtitle=subtitle});var plain=await engine.Thumbnail(first,2);var subtitled=await engine.Thumbnail(sub.Output,2);Check(!plain.SequenceEqual(subtitled),"Subtitle file with spaces, apostrophe and punctuation is rendered");

AppBuilder.Configure<App>().UseSkia().UseHeadless(new AvaloniaHeadlessPlatformOptions{UseHeadlessDrawing=false}).SetupWithoutStarting();Motion.SetReducedMotion(true);
void Pump(){Dispatcher.UIThread.RunJobs();AvaloniaHeadlessPlatform.ForceRenderTimerTick();Dispatcher.UIThread.RunJobs();}
void Until(Func<bool> condition){var stop=DateTime.UtcNow.AddSeconds(30);while(!condition()){Pump();Thread.Sleep(15);if(DateTime.UtcNow>stop)throw new TimeoutException();}Pump();}
T Find<T>(Window w,string name) where T:Control=>w.GetVisualDescendants().OfType<T>().Single(c=>c.Name==name);
Button Button(Window w,string content)=>w.GetVisualDescendants().OfType<Button>().Single(b=>Equals(b.Content,Localization.Text(content)));
void Click(Button button){button.RaiseEvent(new RoutedEventArgs(Avalonia.Controls.Button.ClickEvent));Pump();}
var state=new Storage(Path.Combine(root,"state"));var options=new ConversionOptions{Format="mp4",Speed=1.3,FadeIn=.7,FadeOut=.9};
var editor=new EditorWindow(engine,first,options);editor.Show();Until(()=>editor.Ready.IsCompleted);var read=editor.ReadDraft();Check(read.Speed==1.3&&read.FadeIn==.7&&read.FadeOut==.9,"Editor retains custom speed and fades");
Find<TabControl>(editor,"EditTabs").SelectedIndex=1;Pump();Find<TextBox>(editor,"CropX").Text="20";Find<TextBox>(editor,"CropY").Text="10";Find<TextBox>(editor,"CropWidth").Text="200";Find<TextBox>(editor,"CropHeight").Text="100";
Find<CheckBox>(editor,"DelogoMode").IsChecked=true;Pump();Find<TextBox>(editor,"CropX").Text="40";Find<TextBox>(editor,"CropY").Text="20";Find<TextBox>(editor,"CropWidth").Text="60";Find<TextBox>(editor,"CropHeight").Text="40";Find<CheckBox>(editor,"DelogoMode").IsChecked=false;Pump();read=editor.ReadDraft();Check(read.CropX==20&&read.CropWidth==200&&read.DelogoX==40&&read.DelogoWidth==60,"Switching crop and watermark preserves both regions");
Find<CheckBox>(editor,"DelogoMode").IsChecked=true;Pump();Click(Button(editor,"重置选区"));read=editor.ReadDraft();Check(read.DelogoWidth==0&&read.CropWidth==200,"Reset disables only the selected watermark region");
editor.CaptureRenderedFrame()!.Save(Path.Combine(root,"editor.png"));editor.Close();Pump();
var audioEditor=new EditorWindow(engine,first,new(){Format="wav",AudioFadeIn=.7,AudioFadeOut=.9});audioEditor.Show();Until(()=>audioEditor.Ready.IsCompleted);Check(audioEditor.ReadDraft().AudioFadeIn==.7&&audioEditor.ReadDraft().AudioFadeOut==.9,"Audio editor retains independent audio fades");Check(!((TabItem)Find<TabControl>(audioEditor,"EditTabs").Items[1]!).IsVisible,"Audio editor hides unused video crop controls");audioEditor.Close();Pump();
var config=new OptionsWindow(options,presetStorage:state);config.Show();Pump();Click(Button(config,"另存为…"));var popup=config.OwnedWindows.Single();var name=popup.GetVisualDescendants().OfType<TextBox>().Single();name.Text="已验证预设";Click(Button(popup,"保存"));Until(()=>state.LoadPresets().Count==1);Check(state.LoadPresets().Single().Value.Speed==1.3,"Preset save persists real settings");Click(Button(config,"默认"));Check(config.ReadOptions().Speed==1&&config.ReadOptions().FadeIn==0,"Default button resets output settings");Find<ComboBox>(config,"PresetCombo").SelectedItem="已验证预设";Pump();Check(config.ReadOptions().Speed==1.3&&config.ReadOptions().FadeIn==.7,"Preset selection restores saved settings");config.Close();
foreach(var kind in Enum.GetValues<MediaOptionsKind>()){var window=new OptionsWindow(new(){Format=kind==MediaOptionsKind.Image?"png":"mp4"},kind:kind,presetStorage:state);window.Show();Pump();Check(window.ReadOptions().Format==(kind==MediaOptionsKind.Image?"png":"mp4"),"Configuration page works: "+kind);window.Close();}
state.SaveSettings(new(){Theme="Dark",NotifyComplete=false,OutputFolder=root});var queued=new Job{Inputs=[first],Output=Path.Combine(root,"test.mp4")};state.SaveJobs([queued]);var main=new MainWindow(state);main.Show();Pump();Check(Application.Current!.RequestedThemeVariant==ThemeVariant.Dark,"Saved theme is restored on startup");
var previewTemplate=Find<ListBox>(main,"JobList");var previewButton=previewTemplate.GetVisualDescendants().OfType<Button>().First();Click(previewButton);Until(()=>main.OwnedWindows.OfType<EditorWindow>().Any());var previewEditor=main.OwnedWindows.OfType<EditorWindow>().Single();Until(()=>previewEditor.Ready.IsCompleted);Find<TextBox>(previewEditor,"StartTime").Text="00:00:00.500";Find<TextBox>(previewEditor,"EndTime").Text="00:00:02.000";Click(Find<Button>(previewEditor,"ConfirmButton"));Until(()=>!main.OwnedWindows.Any());Check(state.LoadJobs().Single().Options.Start==.5&&state.LoadJobs().Single().Options.End==2,"Queue preview opens real editor and persists confirmed parameters");
var convert=new ConvertWindow(engine,Catalog.Find("mp4"),root,[first,second]);var requestTask=convert.ShowDialog<ConversionRequest?>(main);Pump();var list=convert.GetVisualDescendants().OfType<ListBox>().Single();list.SelectedIndex=0;Click(Button(convert,"选项 / 剪辑"));Until(()=>convert.OwnedWindows.OfType<EditorWindow>().Any());var fileEditor=convert.OwnedWindows.OfType<EditorWindow>().Single();Until(()=>fileEditor.Ready.IsCompleted);Find<TextBox>(fileEditor,"StartTime").Text="00:00:00.500";Find<TextBox>(fileEditor,"EndTime").Text="00:00:02.000";Click(Find<Button>(fileEditor,"ConfirmButton"));Until(()=>!convert.OwnedWindows.Any());Click(Button(convert,"确定"));Until(()=>requestTask.IsCompleted);var request=requestTask.Result!;Check(request.InputOptions![0].Start==.5&&request.InputOptions[0].End==2&&request.InputOptions[1].Start==0&&request.InputOptions[1].End==0,"Generic conversion retains independent per-file editing");
var editedJob=new Job{FeatureId="mp4",Inputs=[first],Options=request.InputOptions[0],Output=Path.Combine(root,"ui-edited.mp4")};Task.Run(()=>engine.Execute(editedJob,_=>{},CancellationToken.None)).GetAwaiter().GetResult();outputs.Add(editedJob.Output);Check(Task.Run(()=>engine.Probe(editedJob.Output)).GetAwaiter().GetResult().Duration is >1.45 and <1.7,"UI-edited parameters generate the expected media interval");
var batchInput=Path.Combine(root,"batch-owned.mp4");File.Copy(first,batchInput);var journal=Path.Combine(root,"batch-journal.json");var batch=new BatchToolsWindow(engine,root,[batchInput],journal);batch.Show();Pump();Click(Button(batch,"预览新名称"));var entry=batch.GetVisualDescendants().OfType<ListBox>().Single().Items.Cast<BatchVideoEntry>().Single();var renamed=Path.Combine(root,entry.NewName);Click(Button(batch,"执行重命名"));Until(()=>File.Exists(renamed)&&Button(batch,"撤销上一次重命名").IsEnabled);Check(File.Exists(renamed)&&!File.Exists(batchInput)&&batch.OwnedWindows.Count()==0,"Batch rename executes the reviewed plan without another confirmation");Click(Button(batch,"撤销上一次重命名"));Until(()=>File.Exists(batchInput)&&!File.Exists(renamed)&&!Button(batch,"撤销上一次重命名").IsEnabled);Check(File.Exists(batchInput),"Batch undo restores the original file through its button");batch.Close();Pump();
var cropMenu=main.FindControl<MenuItem>("BatchCropMenuItem")!;cropMenu.RaiseEvent(new RoutedEventArgs(MenuItem.ClickEvent));Until(()=>main.OwnedWindows.OfType<BatchCropWindow>().Any());var cropWindow=main.OwnedWindows.OfType<BatchCropWindow>().Single();cropWindow.AddFiles([first,second]);var cropReady=cropWindow.Ready;Until(()=>cropReady.IsCompleted);Find<ListBox>(cropWindow,"FileList").SelectedIndex=0;Pump();Click(Button(cropWindow,"重置为当前全画面"));cropWindow.SetArea(new(21,20,200,100));Pump();Check(!Find<Button>(cropWindow,"OkButton").IsEnabled,"Batch crop validates a shared odd-pixel region before submission");cropWindow.SetArea(new(20,20,200,100));Find<ComboBox>(cropWindow,"ModeCombo").SelectedItem=BatchCropWindow.RelativeMode;Pump();var relative=BatchCrop.CreateJobs(cropWindow.CreateRequest());foreach(var job in relative){Task.Run(()=>engine.Execute(job,_=>{},CancellationToken.None)).GetAwaiter().GetResult();outputs.Add(job.Output);}var relativeInfo=Task.Run(()=>engine.Probe(relative[1].Output)).GetAwaiter().GetResult();Check(relativeInfo.Width==150&&relativeInfo.Height==178,"Shared relative crop creates correct output on a differently sized video");cropWindow.CaptureRenderedFrame()!.Save(Path.Combine(root,"batch-crop.png"));Find<ComboBox>(cropWindow,"ModeCombo").SelectedItem=BatchCropWindow.PixelMode;Pump();Click(Button(cropWindow,"批量加入队列"));Until(()=>!main.OwnedWindows.Any());Check(state.LoadJobs().Count==3,"Batch crop menu submits both videos to the real queue");Click(Find<Button>(main,"StartButton"));Until(()=>state.LoadJobs().All(job=>job.State==JobState.Completed));var cropJobs=state.LoadJobs().Where(job=>job.FeatureId=="crop").ToArray();foreach(var job in cropJobs){var info=Task.Run(()=>engine.Probe(job.Output)).GetAwaiter().GetResult();Check(info.Width==200&&info.Height==100,"Shared pixel crop queue produces 200 x 100 media: "+Path.GetFileName(job.Inputs[0]));outputs.Add(job.Output);}main.Close();Pump();
File.WriteAllText(Path.Combine(root,"report.json"),JsonSerializer.Serialize(new{checks=results.Count,results,outputs},new JsonSerializerOptions{WriteIndented=true}));Console.WriteLine($"Verified {results.Count} checks / {outputs.Count} actual outputs. {root}");
