<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup><OutputType>Exe</OutputType><TargetFramework>net8.0</TargetFramework></PropertyGroup>
  <ItemGroup><ProjectReference Include="../../src/AvaMedia.Desktop/AvaMedia.Desktop.csproj"/><PackageReference Include="Avalonia.Headless" Version="11.3.22"/></ItemGroup>
</Project>
