using System.Text.Json;
using System.Security.Cryptography;
using Avalonia.Media.Imaging;
using Avalonia.Platform;
using Avalonia;
using Avalonia.Controls;
using Avalonia.Controls.Presenters;
using Avalonia.Headless;
using Avalonia.Input;
using Avalonia.Interactivity;
using Avalonia.Media;
using Avalonia.Styling;
using Avalonia.Threading;
using Avalonia.VisualTree;
using AvaMedia.Core;
using AvaMedia.Desktop;
using AvaMedia.Desktop.Controls;

var root = Path.GetFullPath("artifacts/skins-" + DateTime.Now.ToString("yyyyMMdd-HHmmss")); Directory.CreateDirectory(root);
var checks = new List<string>();
void Check(bool value, string text) { if (!value) throw new Exception(text); checks.Add(text); Console.WriteLine("PASS " + text); }
AppBuilder.Configure<App>().UseSkia().UseHeadless(new AvaloniaHeadlessPlatformOptions { UseHeadlessDrawing = false }).SetupWithoutStarting();
Motion.SetReducedMotion(true);
void Pump() { Dispatcher.UIThread.RunJobs(); AvaloniaHeadlessPlatform.ForceRenderTimerTick(); Dispatcher.UIThread.RunJobs(); }
void Capture(Window window, string name) { Pump(); window.CaptureRenderedFrame()!.Save(Path.Combine(root, name + ".png")); }
void Click(Button button) { button.RaiseEvent(new RoutedEventArgs(Button.ClickEvent)); Pump(); }
string Color(IBrush? brush) => brush is ISolidColorBrush color ? color.Color.ToString() : "";
// Compare each control's actual artwork while its containing window stays open.
var iconKinds = Catalog.All.Select(f => f.Icon).Append("clip-list").Distinct().ToArray();
Check(iconKinds.All(kind => AssetLoader.Exists(new Uri($"avares://AvaMedia.Desktop/Assets/FeatureIcons/macos9/{kind}.png"))), "Mac OS 9 embeds artwork for every functional icon kind");
var iconControls = iconKinds.Select(kind => new FeatureIcon { Kind = kind, Width = 92, Height = 80 }).ToArray();
var iconPanel = new WrapPanel { Width = 460 };
foreach (var icon in iconControls) iconPanel.Children.Add(icon);
var iconWindow = new Window { Content = iconPanel, Width = 500, Height = 400 };
Skin.Apply("Light"); iconWindow.Show(); Pump();
string ArtworkHash(FeatureIcon icon)
{
    using var bitmap = new RenderTargetBitmap(new PixelSize(92,80), new Vector(96,96));
    bitmap.Render(icon);
    using var stream = new MemoryStream(); bitmap.Save(stream);
    return Convert.ToHexString(SHA256.HashData(stream.ToArray()));
}
var normalArtwork = iconControls.Select(ArtworkHash).ToArray();
Skin.Apply("MacOS9"); Pump();
for (var i = 0; i < iconControls.Length; i++)
    Check(iconControls[i].ActualThemeVariant == Skin.MacOS9 && ArtworkHash(iconControls[i]) != normalArtwork[i], $"An existing {iconKinds[i]} icon switches to independent Mac OS 9 artwork");
var classicRotate = ArtworkHash(iconControls.Single(icon => icon.Kind == "rotate"));
var childIcon = new FeatureIcon { Kind = "rotate", Width = 92, Height = 80 };
var iconChild = new Window { Content = childIcon, Width = 140, Height = 140 };
iconChild.Show(iconWindow); Pump();
Check(childIcon.ActualThemeVariant == Skin.MacOS9 && ArtworkHash(childIcon) == classicRotate, "A newly opened child window uses the same Mac OS 9 artwork");
Skin.Apply("Dark"); Pump();
Check(iconControls.Select(ArtworkHash).SequenceEqual(normalArtwork), "Switching to Dark restores all original icons without stale Mac OS 9 cache entries");
Skin.Apply("Light"); Pump();
Check(iconControls.Select(ArtworkHash).SequenceEqual(normalArtwork), "Switching to Light restores all original icons");
iconChild.Close(); iconWindow.Close();
var button = new Button { Content = "转换 Convert", Width = 170 };
var input = new TextBox { Text = "中文路径与参数 / Input" };
var combo = new ComboBox { ItemsSource = new[] { "MP4", "MKV", "WebM" }, SelectedIndex = 0 };
var checkbox = new CheckBox { Content = "保留音轨", IsChecked = true };
var slider = new Slider { Value = 40, Maximum = 100 };
var tabs = new TabControl { Items = { new TabItem { Header = "视频", Content = input }, new TabItem { Header = "音频", Content = new TextBlock { Text = "音频选项" } } } };
var original = new StackPanel { Margin = new(20), Spacing = 14, Children = { new TextBlock { Text = "Mac OS 9 · Platinum", FontSize = 18 }, button, combo, checkbox, slider, new ProgressBar { Value = 55 }, tabs } };
var window = new Window { Title = "组件与交互 / Components", Content = original, Width = 620, Height = 520 };
window.Show(); Pump(); Capture(window, "components-light");
var originalDecorations = window.SystemDecorations;
Skin.Apply("MacOS9"); Pump();
Check(window.ActualThemeVariant == Skin.MacOS9 && window.Classes.Contains("mac-os9"), "An open window switches to Mac OS 9");
Check(window.Content is PlatinumWindowFrame && window.SystemDecorations == SystemDecorations.None, "Platinum chrome replaces native decoration");
Check(Color(window.Background) == "#ffcccccc", "Platinum palette resolves through the custom theme variant");
Check(button.GetVisualDescendants().OfType<PlatinumBevel>().Any(), "Buttons use the shared vector bevel template");
Check(checkbox.GetVisualDescendants().OfType<Avalonia.Controls.Shapes.Path>().Single(p => p.Name == "checkMark").Stroke is not null, "The checked box uses a classic cross mark");
Check(Color(slider.GetVisualDescendants().OfType<PlatinumBevel>().Single().Background) == "#ffbbbbbb", "The slider thumb inherits the Platinum control theme");
Check(input.Text == "中文路径与参数 / Input" && combo.SelectedIndex == 0 && checkbox.IsChecked == true, "Skin switching retains control state");
var face = button.GetVisualDescendants().OfType<PlatinumBevel>().Single();
button.Focus(NavigationMethod.Tab); Pump(); Check(face.IsFocusedFace, "Keyboard focus has an immediate visible bezel");
var buttonPoint = button.TranslatePoint(new Point(20, 12), window)!.Value;
window.MouseDown(buttonPoint, MouseButton.Left); Pump(); Check(face.IsPressed, "Pointer press uses an inset bevel");
window.MouseUp(buttonPoint, MouseButton.Left); Pump(); Check(!face.IsPressed, "Releasing the pointer restores the raised bevel");
var clicks = 0; button.Click += (_, _) => clicks++; Click(button); Check(clicks == 1, "The skinned button keeps its action");
button.IsEnabled = false; Pump(); Check(!button.IsEnabled && button.Opacity < 1, "Disabled controls remain disabled and visibly distinct"); button.IsEnabled = true;
combo.IsDropDownOpen = true; Pump(); Check(combo.IsDropDownOpen, "The skinned combo box opens its real popup"); combo.SelectedIndex = 1; combo.IsDropDownOpen = false;
tabs.SelectedIndex = 1; Pump(); Check(tabs.SelectedIndex == 1, "The skinned tabs keep selection behavior"); tabs.SelectedIndex = 0;
Capture(window, "components-macos9");
var options = new OptionsWindow(new() { Format = "mkv" }); options.Show(window); Pump();
Check(options.Content is PlatinumWindowFrame && options.ActualThemeVariant == Skin.MacOS9, "A newly opened options window inherits the skin");
Capture(options, "options-macos9");
Application.Current!.RequestedThemeVariant = ThemeVariant.Dark; Pump();
Check(ReferenceEquals(window.Content, original) && window.SystemDecorations == originalDecorations, "Switching back restores the original content and native chrome");
Check(options.Content is not PlatinumWindowFrame && Color(window.Background) == "#ff202020", "Switching also restores an already open child window");
Check(input.Text == "中文路径与参数 / Input" && combo.SelectedIndex == 1, "Content reparenting preserves the edited values");
Capture(window, "components-dark"); options.Close(); window.Close();

var state = new Storage(Path.Combine(root, "isolated-state")); state.SaveSettings(new() { Theme = "MacOS9", ReduceMotion = true, NotifyComplete = false });
var main = new MainWindow(state); main.Show(); Pump();
Check(main.Content is PlatinumWindowFrame && main.ActualThemeVariant == Skin.MacOS9, "A saved Mac OS 9 skin is restored at startup");
Capture(main, "main-macos9");
var item = main.GetVisualDescendants().OfType<Menu>().First().Items.OfType<MenuItem>().Single(i => Equals(i.Header, "皮肤")).Items.OfType<MenuItem>().Single(i => Equals(i.Header, "深色"));
item.RaiseEvent(new RoutedEventArgs(MenuItem.ClickEvent)); Pump(); Check(state.LoadSettings().Theme == "Dark", "The skin menu saves the selected theme");
main.GetVisualDescendants().OfType<Menu>().First().Items.OfType<MenuItem>().Single(i => Equals(i.Header, "皮肤")).Items.OfType<MenuItem>().Single(i => Equals(i.Header, "Mac OS 9 · Platinum")).RaiseEvent(new RoutedEventArgs(MenuItem.ClickEvent)); Pump();
Check(state.LoadSettings().Theme == "MacOS9" && main.Content is PlatinumWindowFrame, "The Mac OS 9 menu action changes and persists the skin");
var frame = (PlatinumWindowFrame)main.Content!;
var zoom = frame.GetVisualDescendants().OfType<Button>().Single(b => b.Name == "PlatinumZoom"); Click(zoom); Check(main.WindowState == WindowState.Maximized, "The custom zoom button maximizes the window"); Click(zoom); Check(main.WindowState == WindowState.Normal, "The custom zoom button restores the window");
main.Title = "Platinum Title Updated"; Pump(); Check(frame.GetVisualDescendants().OfType<TextBlock>().Any(t => t.Text == main.Title), "The custom caption follows window title changes");
main.CanMaximize = false; main.CanMinimize = false; Pump();
Check(!zoom.IsEnabled && !frame.GetVisualDescendants().OfType<Button>().Single(b => b.Name == "PlatinumMinimize").IsEnabled, "Caption buttons respect window capabilities");
main.CanMaximize = true; main.CanMinimize = true; main.CanResize = false; Pump();
Check(!zoom.IsEnabled, "A fixed-size window cannot be zoomed by its custom caption");
main.CanResize = true;
var close = frame.GetVisualDescendants().OfType<Button>().Single(b => b.Name == "PlatinumClose");
EventHandler<WindowClosingEventArgs> cancelClose = (_, e) => e.Cancel = true;
main.Closing += cancelClose; Click(close); Check(main.IsVisible, "The custom close button honors a cancelled Closing event");
main.Closing -= cancelClose; Click(close); Check(!main.IsVisible, "The custom close button runs the real window closing path");
var replacement = new TextBox { Text = "Replacement content" };
var replaced = new Window { Content = new TextBlock { Text = "Original" }, Width = 320, Height = 160 }; replaced.Show(); Pump();
replaced.Content = replacement; Pump(); Check(replaced.Content is PlatinumWindowFrame, "Replacing window content reapplies the frame without nested chrome");
Skin.Apply("Light");
Pump(); Check(ReferenceEquals(replaced.Content, replacement), "Returning to Light restores the replacement content"); replaced.Close();
File.WriteAllText(Path.Combine(root, "report.json"), JsonSerializer.Serialize(new { checks = checks.Count, results = checks }, new JsonSerializerOptions { WriteIndented = true }));
Console.WriteLine($"Verified {checks.Count} skin checks. {root}");
